# Dictionary of countries that can be used on players' roster information.

from discord import app_commands

COUNTRIES = {
    "A": [
        app_commands.Choice(name="🇦🇫 Afghanistan", value="Afghanistan"),
        app_commands.Choice(name="🇦🇱 Albania", value="Albania"),
        app_commands.Choice(name="🇩🇿 Algeria", value="Algeria"),
        app_commands.Choice(name="🇦🇩 Andorra", value="Andorra"),
        app_commands.Choice(name="🇦🇴 Angola", value="Angola"),
        app_commands.Choice(name="🇦🇬 Antigua and Barbuda", value="Antigua and Barbuda"),
        app_commands.Choice(name="🇦🇷 Argentina", value="Argentina"),
        app_commands.Choice(name="🇦🇲 Armenia", value="Armenia"),
        app_commands.Choice(name="🇦🇺 Australia", value="Australia"),
        app_commands.Choice(name="🇦🇹 Austria", value="Austria"),
        app_commands.Choice(name="🇦🇿 Azerbaijan", value="Azerbaijan"),
    ],

    "B": [
        app_commands.Choice(name="🇧🇸 Bahamas", value="Bahamas"),
        app_commands.Choice(name="🇧🇭 Bahrain", value="Bahrain"),
        app_commands.Choice(name="🇧🇩 Bangladesh", value="Bangladesh"),
        app_commands.Choice(name="🇧🇧 Barbados", value="Barbados"),
        app_commands.Choice(name="🇧🇾 Belarus", value="Belarus"),
        app_commands.Choice(name="🇧🇪 Belgium", value="Belgium"),
        app_commands.Choice(name="🇧🇿 Belize", value="Belize"),
        app_commands.Choice(name="🇧🇯 Benin", value="Benin"),
        app_commands.Choice(name="🇧🇹 Bhutan", value="Bhutan"),
        app_commands.Choice(name="🇧🇴 Bolivia", value="Bolivia"),
        app_commands.Choice(name="🇧🇦 Bosnia and Herzegovina", value="Bosnia and Herzegovina"),
        app_commands.Choice(name="🇧🇼 Botswana", value="Botswana"),
        app_commands.Choice(name="🇧🇷 Brazil", value="Brazil"),
        app_commands.Choice(name="🇧🇳 Brunei", value="Brunei"),
        app_commands.Choice(name="🇧🇬 Bulgaria", value="Bulgaria"),
        app_commands.Choice(name="🇧🇫 Burkina Faso", value="Burkina Faso"),
        app_commands.Choice(name="🇧🇮 Burundi", value="Burundi"),
    ],

    "C": [
        app_commands.Choice(name="🇨🇻 Cabo Verde", value="Cabo Verde"),
        app_commands.Choice(name="🇰🇭 Cambodia", value="Cambodia"),
        app_commands.Choice(name="🇨🇲 Cameroon", value="Cameroon"),
        app_commands.Choice(name="🇨🇦 Canada", value="Canada"),
        app_commands.Choice(name="🇨🇫 Central African Republic", value="Central African Republic"),
        app_commands.Choice(name="🇹🇩 Chad", value="Chad"),
        app_commands.Choice(name="🇨🇱 Chile", value="Chile"),
        app_commands.Choice(name="🇨🇳 China", value="China"),
        app_commands.Choice(name="🇨🇴 Colombia", value="Colombia"),
        app_commands.Choice(name="🇰🇲 Comoros", value="Comoros"),
        app_commands.Choice(name="🇨🇬 Congo (Republic)", value="Congo (Republic)"),
        app_commands.Choice(name="🇨🇷 Costa Rica", value="Costa Rica"),
        app_commands.Choice(name="🇨🇮 Côte d'Ivoire", value="Côte d'Ivoire"),
        app_commands.Choice(name="🇭🇷 Croatia", value="Croatia"),
        app_commands.Choice(name="🇨🇺 Cuba", value="Cuba"),
        app_commands.Choice(name="🇨🇾 Cyprus", value="Cyprus"),
        app_commands.Choice(name="🇨🇿 Czech Republic", value="Czech Republic"),
    ],

    "D": [
        app_commands.Choice(name="🇩🇰 Denmark", value="Denmark"),
        app_commands.Choice(name="🇩🇯 Djibouti", value="Djibouti"),
        app_commands.Choice(name="🇩🇲 Dominica", value="Dominica"),
        app_commands.Choice(name="🇩🇴 Dominican Republic", value="Dominican Republic"),
        app_commands.Choice(name="🇰🇵 DPR Korea", value="DPR Korea"),
        app_commands.Choice(name="🇨🇩 DR Congo", value="DR Congo"),
    ],

    "E": [
        app_commands.Choice(name="🇪🇨 Ecuador", value="Ecuador"),
        app_commands.Choice(name="🇪🇬 Egypt", value="Egypt"),
        app_commands.Choice(name="🇸🇻 El Salvador", value="El Salvador"),
        app_commands.Choice(name="🇬🇶 Equatorial Guinea", value="Equatorial Guinea"),
        app_commands.Choice(name="🇪🇷 Eritrea", value="Eritrea"),
        app_commands.Choice(name="🇪🇪 Estonia", value="Estonia"),
        app_commands.Choice(name="🇸🇿 Eswatini", value="Eswatini"),
        app_commands.Choice(name="🇪🇹 Ethiopia", value="Ethiopia"),
    ],

    "F": [
        app_commands.Choice(name="🇫🇯 Fiji", value="Fiji"),
        app_commands.Choice(name="🇫🇮 Finland", value="Finland"),
        app_commands.Choice(name="🇫🇷 France", value="France"),
        app_commands.Choice(name="🇬🇫 French Guiana", value="French Guiana"),
        app_commands.Choice(name="🇵🇫 French Polynesia", value="French Polynesia"),
        app_commands.Choice(name="🇹🇫 French Southern Territories", value="French Southern Territories"),
    ],

    "G": [
        app_commands.Choice(name="🇬🇦 Gabon", value="Gabon"),
        app_commands.Choice(name="🇬🇲 Gambia", value="Gambia"),
        app_commands.Choice(name="🇬🇪 Georgia", value="Georgia"),
        app_commands.Choice(name="🇩🇪 Germany", value="Germany"),
        app_commands.Choice(name="🇬🇭 Ghana", value="Ghana"),
        app_commands.Choice(name="🇬🇷 Greece", value="Greece"),
        app_commands.Choice(name="🇬🇩 Grenada", value="Grenada"),
        app_commands.Choice(name="🇬🇹 Guatemala", value="Guatemala"),
        app_commands.Choice(name="🇬🇳 Guinea", value="Guinea"),
        app_commands.Choice(name="🇬🇼 Guinea-Bissau", value="Guinea-Bissau"),
        app_commands.Choice(name="🇬🇾 Guyana", value="Guyana"),
        app_commands.Choice(name="🇬🇮 Gibraltar", value="Gibraltar"),
    ],

    "H": [
        app_commands.Choice(name="🇭🇹 Haiti", value="Haiti"),
        app_commands.Choice(name="🇭🇳 Honduras", value="Honduras"),
        app_commands.Choice(name="🇭🇺 Hungary", value="Hungary"),
        app_commands.Choice(name="🇭🇰 Hong Kong", value="Hong Kong"),
    ],

    "I": [
        app_commands.Choice(name="🇮🇸 Iceland", value="Iceland"),
        app_commands.Choice(name="🇮🇳 India", value="India"),
        app_commands.Choice(name="🇮🇩 Indonesia", value="Indonesia"),
        app_commands.Choice(name="🇮🇷 Iran", value="Iran"),
        app_commands.Choice(name="🇮🇶 Iraq", value="Iraq"),
        app_commands.Choice(name="🇮🇪 Ireland", value="Ireland"),
        app_commands.Choice(name="🇮🇱 Israel", value="Israel"),
        app_commands.Choice(name="🇮🇹 Italy", value="Italy"),
    ],

    "J": [
        app_commands.Choice(name="🇯🇲 Jamaica", value="Jamaica"),
        app_commands.Choice(name="🇯🇵 Japan", value="Japan"),
        app_commands.Choice(name="🇯🇴 Jordan", value="Jordan"),
    ],
    
    "K": [
        app_commands.Choice(name="🇰🇿 Kazakhstan", value="Kazakhstan"),
        app_commands.Choice(name="🇰🇪 Kenya", value="Kenya"),
        app_commands.Choice(name="🇰🇮 Kiribati", value="Kiribati"),
        app_commands.Choice(name="🇽🇰 Kosovo", value="Kosovo"),
        app_commands.Choice(name="🇰🇼 Kuwait", value="Kuwait"),
        app_commands.Choice(name="🇰🇬 Kyrgyzstan", value="Kyrgyzstan"),
    ],

    "L": [
        app_commands.Choice(name="🇱🇦 Laos", value="Laos"),
        app_commands.Choice(name="🇱🇻 Latvia", value="Latvia"),
        app_commands.Choice(name="🇱🇧 Lebanon", value="Lebanon"),
        app_commands.Choice(name="🇱🇸 Lesotho", value="Lesotho"),
        app_commands.Choice(name="🇱🇷 Liberia", value="Liberia"),
        app_commands.Choice(name="🇱🇾 Libya", value="Libya"),
        app_commands.Choice(name="🇱🇮 Liechtenstein", value="Liechtenstein"),
        app_commands.Choice(name="🇱🇹 Lithuania", value="Lithuania"),
        app_commands.Choice(name="🇱🇺 Luxembourg", value="Luxembourg"),
    ],

    "M": [
        app_commands.Choice(name="🇲🇬 Madagascar", value="Madagascar"),
        app_commands.Choice(name="🇲🇼 Malawi", value="Malawi"),
        app_commands.Choice(name="🇲🇾 Malaysia", value="Malaysia"),
        app_commands.Choice(name="🇲🇻 Maldives", value="Maldives"),
        app_commands.Choice(name="🇲🇱 Mali", value="Mali"),
        app_commands.Choice(name="🇲🇹 Malta", value="Malta"),
        app_commands.Choice(name="🇲🇭 Marshall Islands", value="Marshall Islands"),
        app_commands.Choice(name="🇲🇶 Martinique", value="Martinique"),
        app_commands.Choice(name="🇲🇷 Mauritania", value="Mauritania"),
        app_commands.Choice(name="🇲🇺 Mauritius", value="Mauritius"),
        app_commands.Choice(name="🇾🇹 Mayotte", value="Mayotte"),
        app_commands.Choice(name="🇲🇽 Mexico", value="Mexico"),
        app_commands.Choice(name="🇫🇲 Micronesia", value="Micronesia"),
        app_commands.Choice(name="🇲🇩 Moldova", value="Moldova"),
        app_commands.Choice(name="🇲🇨 Monaco", value="Monaco"),
        app_commands.Choice(name="🇲🇳 Mongolia", value="Mongolia"),
        app_commands.Choice(name="🇲🇪 Montenegro", value="Montenegro"),
        app_commands.Choice(name="🇲🇸 Montserrat", value="Montserrat"),
        app_commands.Choice(name="🇲🇦 Morocco", value="Morocco"),
        app_commands.Choice(name="🇲🇿 Mozambique", value="Mozambique"),
        app_commands.Choice(name="🇲🇲 Myanmar", value="Myanmar"),
    ],

    "N": [
        app_commands.Choice(name="🇳🇦 Namibia", value="Namibia"),
        app_commands.Choice(name="🇳🇷 Nauru", value="Nauru"),
        app_commands.Choice(name="🇳🇵 Nepal", value="Nepal"),
        app_commands.Choice(name="🇳🇱 Netherlands", value="Netherlands"),
        app_commands.Choice(name="🇳🇨 New Caledonia", value="New Caledonia"),
        app_commands.Choice(name="🇳🇿 New Zealand", value="New Zealand"),
        app_commands.Choice(name="🇳🇮 Nicaragua", value="Nicaragua"),
        app_commands.Choice(name="🇳🇪 Niger", value="Niger"),
        app_commands.Choice(name="🇳🇬 Nigeria", value="Nigeria"),
        app_commands.Choice(name="🇳🇺 Niue", value="Niue"),
        app_commands.Choice(name="🇳🇫 Norfolk Island", value="Norfolk Island"),
        app_commands.Choice(name="🇲🇰 North Macedonia", value="North Macedonia"),
        app_commands.Choice(name="🇳🇴 Norway", value="Norway"),
    ],

    "O": [
        app_commands.Choice(name="🇴🇲 Oman", value="Oman"),
    ],

    "P": [
        app_commands.Choice(name="🇵🇰 Pakistan", value="Pakistan"),
        app_commands.Choice(name="🇵🇼 Palau", value="Palau"),
        app_commands.Choice(name="🇵🇸 Palestinian Territories", value="Palestinian Territories"),
        app_commands.Choice(name="🇵🇦 Panama", value="Panama"),
        app_commands.Choice(name="🇵🇬 Papua New Guinea", value="Papua New Guinea"),
        app_commands.Choice(name="🇵🇾 Paraguay", value="Paraguay"),
        app_commands.Choice(name="🇵🇪 Peru", value="Peru"),
        app_commands.Choice(name="🇵🇭 Philippines", value="Philippines"),
        app_commands.Choice(name="🇵🇱 Poland", value="Poland"),
        app_commands.Choice(name="🇵🇹 Portugal", value="Portugal"),
    ],

    "Q": [
        app_commands.Choice(name="🇶🇦 Qatar", value="Qatar"),
    ],

    "R": [
        app_commands.Choice(name="🇷🇼 Rwanda", value="Rwanda"),
        app_commands.Choice(name="🇷🇴 Romania", value="Romania"),
        app_commands.Choice(name="🇷🇺 Russian Federation", value="Russian Federation"),
        app_commands.Choice(name="🇰🇷 Republic of Korea", value="Republic of Korea"),
        app_commands.Choice(name="🇷🇪 Réunion", value="Réunion"),
    ],

    "S": [
        app_commands.Choice(name="🇰🇳 Saint Kitts and Nevis", value="Saint Kitts and Nevis"),
        app_commands.Choice(name="🇱🇨 Saint Lucia", value="Saint Lucia"),
        app_commands.Choice(name="🇻🇨 Saint Vincent and the Grenadines", value="Saint Vincent and the Grenadines"),
        app_commands.Choice(name="🇼🇸 Samoa", value="Samoa"),
        app_commands.Choice(name="🇸🇲 San Marino", value="San Marino"),
        app_commands.Choice(name="🇸🇹 Sao Tome and Principe", value="Sao Tome and Principe"),
        app_commands.Choice(name="🇸🇦 Saudi Arabia", value="Saudi Arabia"),
        app_commands.Choice(name="🇸🇳 Senegal", value="Senegal"),
        app_commands.Choice(name="🇷🇸 Serbia", value="Serbia"),
        app_commands.Choice(name="🇸🇨 Seychelles", value="Seychelles"),
        app_commands.Choice(name="🇸🇱 Sierra Leone", value="Sierra Leone"),
        app_commands.Choice(name="🇸🇬 Singapore", value="Singapore"),
        app_commands.Choice(name="🇸🇰 Slovakia", value="Slovakia"),
        app_commands.Choice(name="🇸🇮 Slovenia", value="Slovenia"),
        app_commands.Choice(name="🇸🇧 Solomon Islands", value="Solomon Islands"),
        app_commands.Choice(name="🇸🇴 Somalia", value="Somalia"),
        app_commands.Choice(name="🇿🇦 South Africa", value="South Africa"),
        app_commands.Choice(name="🇸🇸 South Sudan", value="South Sudan"),
        app_commands.Choice(name="🇪🇸 Spain", value="Spain"),
        app_commands.Choice(name="🇱🇰 Sri Lanka", value="Sri Lanka"),
        app_commands.Choice(name="🇸🇩 Sudan", value="Sudan"),
        app_commands.Choice(name="🇸🇷 Suriname", value="Suriname"),
        app_commands.Choice(name="🇸🇪 Sweden", value="Sweden"),
        app_commands.Choice(name="🇨🇭 Switzerland", value="Switzerland"),
        app_commands.Choice(name="🇸🇾 Syria", value="Syria"),
    ],

    "T": [
        app_commands.Choice(name="🇹🇯 Tajikistan", value="Tajikistan"),
        app_commands.Choice(name="🇹🇿 Tanzania", value="Tanzania"),
        app_commands.Choice(name="🇹🇭 Thailand", value="Thailand"),
        app_commands.Choice(name="🇹🇱 Timor-Leste", value="Timor-Leste"),
        app_commands.Choice(name="🇹🇬 Togo", value="Togo"),
        app_commands.Choice(name="🇹🇴 Tonga", value="Tonga"),
        app_commands.Choice(name="🇹🇹 Trinidad and Tobago", value="Trinidad and Tobago"),
        app_commands.Choice(name="🇹🇳 Tunisia", value="Tunisia"),
        app_commands.Choice(name="🇹🇷 Türkiye", value="Türkiye"),
        app_commands.Choice(name="🇹🇲 Turkmenistan", value="Turkmenistan"),
        app_commands.Choice(name="🇹🇻 Tuvalu", value="Tuvalu"),
        app_commands.Choice(name="🇹🇼 Taiwan", value="Taiwan"),
    ],

    "U": [
        app_commands.Choice(name="🇺🇬 Uganda", value="Uganda"),
        app_commands.Choice(name="🇺🇦 Ukraine", value="Ukraine"),
        app_commands.Choice(name="🇦🇪 United Arab Emirates", value="United Arab Emirates"),
        app_commands.Choice(name="🇬🇧 United Kingdom", value="United Kingdom"),
        app_commands.Choice(name="🇺🇸 United States", value="United States"),
        app_commands.Choice(name="🇺🇾 Uruguay", value="Uruguay"),
        app_commands.Choice(name="🇺🇿 Uzbekistan", value="Uzbekistan"),
    ],

    "V": [
        app_commands.Choice(name="🇻🇺 Vanuatu", value="Vanuatu"),
        app_commands.Choice(name="🇻🇦 Vatican City", value="Vatican City"),
        app_commands.Choice(name="🇻🇪 Venezuela", value="Venezuela"),
        app_commands.Choice(name="🇻🇳 Vietnam", value="Vietnam"),
    ],

    "W": [
        app_commands.Choice(name="🇼🇫 Wallis and Futuna", value="Wallis and Futuna"),
        app_commands.Choice(name="🇪🇭 Western Sahara", value="Western Sahara"),
    ],

    "Y": [
        app_commands.Choice(name="🇾🇪 Yemen", value="Yemen"),
    ],

    "Z": [
        app_commands.Choice(name="🇿🇲 Zambia", value="Zambia"),
        app_commands.Choice(name="🇿🇼 Zimbabwe", value="Zimbabwe"),
    ]
}
